language: java
script:
    - mvn clean
    - mvn package
    - mvn exec:exec
    - if ls graal_dumps 2>/dev/null; then echo "No graal_dumps directory expected so far"; exit 1; fi
    - mvn -Pigv test
    - find graal_dumps
    - echo Test dumped data to graal_dumps directory.
    - rm -rf graal_dumps
    - mvn -Pigv exec:exec
    - find graal_dumps
    - echo Run dumped data to graal_dumps directory.

jobs:
    include:
        - name: Linux JDK11 tests
          jdk: openjdk11
          dist: xenial
          os: linux

        - name: Linux JDK15 tests
          jdk: openjdk15
          dist: xenial
          os: linux

        - name: Linux JDK16 tests
          jdk: openjdk16
          dist: xenial
          os: linux

        - name: MacOS JDK11 tests
          language: shell
          os: osx
          osx_image: xcode12
          addons:
            homebrew:
              packages:
                - openjdk@11
              update: true
          install:
            - sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
            - export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
            - export JAVA_HOME=`/usr/libexec/java_home -v 11`

        - name: MacOS JDK15 tests
          language: shell
          os: osx
          osx_image: xcode12
          addons:
            homebrew:
              packages:
                - openjdk@15
              update: true
          install:
            - sudo ln -sfn /usr/local/opt/openjdk@15/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-15.jdk
            - export PATH="/usr/local/opt/openjdk@15/bin:$PATH"
            - export JAVA_HOME=`/usr/libexec/java_home -v 15`
